name: chatapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase: ^9.0.3
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  cloud_firestore: ^5.4.5
  intl: ^0.19.0
  http: ^0.13.6
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  firebase_messaging: ^15.1.5
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/background.jpeg
    - lib/assets/google.png
    - lib/assets/apple.png
    - lib/assets/background.webp
    - lib/assets/serverkey.json

  fonts:
    - family: Tungsten
      fonts:
        - asset: lib/assets/fonts/Tungsten-Bold.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
